// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjxLtujTu4sAXbOM19JOxHzUcJFtW1AcY',
    appId: '1:658094776047:web:8f581ee62626ad4f9a451a',
    messagingSenderId: '658094776047',
    projectId: 'attendance-384502',
    authDomain: 'attendance-384502.firebaseapp.com',
    storageBucket: 'attendance-384502.appspot.com',
    measurementId: 'G-X1SQ13TVWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp5RDWlyDjfPjfcwEyJaKaL60325MbHQg',
    appId: '1:658094776047:android:ec3b65112ffda7689a451a',
    messagingSenderId: '658094776047',
    projectId: 'attendance-384502',
    storageBucket: 'attendance-384502.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmIJuHQGdvtm1-5bKv1RH0saq1bVYHKwc',
    appId: '1:658094776047:ios:ae1dfc4ab1b9c7399a451a',
    messagingSenderId: '658094776047',
    projectId: 'attendance-384502',
    storageBucket: 'attendance-384502.appspot.com',
    iosBundleId: 'com.example.attendence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmIJuHQGdvtm1-5bKv1RH0saq1bVYHKwc',
    appId: '1:658094776047:ios:77e957d20593833e9a451a',
    messagingSenderId: '658094776047',
    projectId: 'attendance-384502',
    storageBucket: 'attendance-384502.appspot.com',
    iosBundleId: 'com.example.attendence.RunnerTests',
  );
}
